import {
  faAngleDown,
  faAngleUp,
  faBolt,
  faCartShopping,
  faChartLine,
  faGasPump
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Head from 'next/head';
import { useState } from 'react';
import Card from '../Components/Card';
import { loadData } from '../utils/load-data';

type HomeProps = {
  data: {
    rawAll: any;
    cpi: string;
    food: string;
    energy: string;
    gas: string;
  };
};

export default function Home(props: HomeProps) {
  const [showDebug, setShowDebug] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="p-4 text-center text-3xl font-bold text-slate-700">CPI Report</h1>
        <h2 className="p-4 text-center text-2xl">Previous 12 Months</h2>
        <div className="mx-auto flex flex-row justify-center gap-4">
          <Card
            title="CPI"
            value={props.data.cpi}
            icon={faChartLine}
            twColorPrimary="text-blue-500"
            twColorBorder="border-blue-300"
          />
          <Card
            title="Food"
            value={props.data.food}
            icon={faCartShopping}
            twColorPrimary="text-green-500"
            twColorBorder="border-green-300"
          />
          <Card
            title="Energy"
            value={props.data.energy}
            icon={faBolt}
            twColorPrimary="text-yellow-500"
            twColorBorder="border-yellow-300"
          />
          <Card
            title="Gas"
            value={props.data.gas}
            icon={faGasPump}
            twColorPrimary="text-orange-500"
            twColorBorder="border-orange-300"
          />
        </div>
        <div className="p-4 text-center text-lg text-slate-700">
          Data Sourced From <a href="https://www.bls.gov/">U.S. BUREAU OF LABOR STATISTICS</a>
        </div>

        <button
          className="mx-auto flex flex-row justify-center rounded-lg bg-gray-900 p-2 font-semibold text-white"
          onClick={() => setShowDebug(!showDebug)}
        >
          {showDebug ? (
            <div className="flex items-center gap-2">
              Hide Debug <FontAwesomeIcon icon={faAngleUp} />
            </div>
          ) : (
            <div className="flex items-center gap-2">
              Show Debug <FontAwesomeIcon icon={faAngleDown} />
            </div>
          )}
        </button>
        {showDebug && (
          <pre className="m-8 rounded-lg bg-gray-800 p-4 text-white">
            {JSON.stringify(props.data.rawAll, null, 2)}
          </pre>
        )}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const data = await loadData();

  return {
    props: { data }
  };
}
